<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-14 09:28

import idea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='code',
            field=models.CharField(default=idea.models.generate_lobby_code, max_length=6, unique=True),
        ),
    ]
=======
# Generated by Django 5.2 on 2025-04-14 09:28

import idea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='code',
            field=models.CharField(default=idea.models.generate_lobby_code, max_length=6, unique=True),
        ),
    ]
>>>>>>> 064c8003ac86536e85c31b9f5f539e66eedc6ff9
