<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_lobby_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
=======
# Generated by Django 5.2 on 2025-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_lobby_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
>>>>>>> 064c8003ac86536e85c31b9f5f539e66eedc6ff9
